# 1. Numpy introduction

**NumPy stands for Numerical Python**, which is a Python library that performs numerical calculations. NumPy is very fast because it is written in the C programming language. `NumPy is built on linear algebra`. It’s about `matrices` and `vectors` and performing the mathematical calculations on them.

The key concept in NumPy is the `NumPy array` data type. A NumPy array may have one or more dimensions:

- One dimension arrays (1D) represent vectors.
- Two-dimensional arrays (2D) represent matrices.
- And higher dimensional arrays represent tensors.

Below figure shows an example of numpy array
![np_array.png](../../../images/np_array.png)

> Unlike python built-in list type (hold elements of different types), NumPy arrays allow only one data type (e.g. integer or float). Therefore, we say that the NumPy array requires homogeneous data values.

NumPy supports basic operations such as:
- average
- minimum
- maximum
- standard deviation
- variance

NumPy is an important library for:

- Data Science
- Machine learning
- Signal and image processing
- Scientific and engineer computing

In [1]:
import numpy as np

For example, the following code creates a new NumPy array that contains three temperatures in celsius

In [13]:
temp_cel = np.array([25.5, 28.1, 30.6])

In [14]:
print(temp_cel)

[25.5 28.1 30.6]


In [15]:
print(type(temp_cel))

<class 'numpy.ndarray'>


Now we want to convert these temperatures from celsius to Kelvin

In [25]:
%%timeit
temp_kel=temp_cel*9/5+32


4.71 µs ± 81.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
print(temp_kel)

[77.9  82.58 87.08]


If we use the python loop, we need to write below code

In [24]:
%%timeit

tk_bis=[c*9/5+32 for c in temp_cel]


1.79 µs ± 56.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
print(tk_bis)

[77.9, 82.58, 87.08000000000001]


NumPy's calculation should be faster than the for loop. But my result shows the for loop is faster

## 1.1 Creating two-dimensional arrays

To create a two dimension array, we pass a list of a list of integers to the array() function. A two-dimensional array is also called a `matrix`.

In [26]:
two_dim=np.array([
    [1,2,3],
    [4,5,6]
])

In [27]:
print(two_dim)

[[1 2 3]
 [4 5 6]]


## 1.2 Creating three-dimensional array

In [28]:
three_dim=np.array([
    [
      [1,2,3],
      [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]

])

In [29]:
print(three_dim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 1.2 Getting the property of a np array

NumPy provides some useful method to get important properties of a np array
- dimension: get the number of dimensions of an array
- element data type
- shape

### get array dimension

In [30]:

print(temp_cel.ndim)

1


In [31]:
print(two_dim.ndim)

2


In [32]:
print(three_dim.ndim)

3


### Get the data type of array elements

In [33]:

print(temp_cel.dtype)

float64


In [34]:
print(two_dim.dtype)

int64


Note the data type is inferred by NumPy during the array creation, when user does not specify any type. User can specify explicitly a type during creation

In [35]:
float_array=np.array([1,2,3],dtype=np.float64)
print(float_array.dtype)

float64


### Get the shape of an array

The shape represents **the number of axes and the number of elements on each axis of an array**

Below figure shows an example:
![np_array_shape.PNG](../../../images/np_array_shape.PNG)

The shape property returns a tuple:

- The number of elements in the tuple is the number of axes.
- Each tuple element stores the number of elements of the corresponding axis.

In [36]:
# in this case, there is only 1 element, so the axes is 1
# the element value is 3, it means there is 3 element in axes 0
print(temp_cel.shape)

(3,)


In [37]:
# in this case, there is 2 element, so the axes is 2
# the 1st element value is 2, it means there is 2 element in axes 0 (2 list)
# the 2nd element value is 3, it means there is 3 element in axes 1 (3 items in list)
print(two_dim.shape)

(2, 3)


In [38]:
# note you can't have inhomogeneous shape. For example, below array can't be created in np
variant=np.array([
    [1,2,3],
    [4,5]
])

print(variant.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.