# 2. Create np array

NumPy provide many method to create np array with static values:
- np.zeros() : create an array with 0 with the given shape
- np.ones(): create a numpy array of a given shape whose elements are filled with ones.
- arange(): create a numpy array with evenly spaced numbers.
- linspace(): create a new numpy array with evenly spaced numbers of a specified interval.

## 2.1 zeros



In [1]:
import numpy as np

zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
print(zeros.dtype)

float64


You can notice by default, zeros() function uses the type float64 for its elements. if you want to use another type, you need to specify it explicitly

In [3]:
zeros_int=np.zeros((2,3),dtype=np.int16)

In [4]:
print(zeros_int)

[[0 0 0]
 [0 0 0]]


In [5]:
print(zeros_int.dtype)

int16


## ones

Ones is similar to zeros

In [6]:
ones=np.ones((2,3,2))
print(ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [7]:
print(ones.dtype)

float64


## arange

The numpy **arange()** function creates a new numpy array with `evenly spaced numbers between start (inclusive) and stop (exclusive) with a given step`.

The general form is:
```python
numpy.arange(start, stop, step, dtype=None, *, like=None)
```

In [8]:
# start is 1, stop is 10, step is 2
a1 = np.arange(1, 10, 2)

print(a1)

[1 3 5 7 9]


In [9]:
print(a1.dtype)

int64


> arange use the dtype of start and stop as the dtype of the array, But you can force it by giving a type

In [10]:
a2 = np.arange(1, 10, 2,dtype=np.float32)

print(a2)

[1. 3. 5. 7. 9.]


In [11]:
print(a2.dtype)

float32


## linspace

The numpy linspace() function creates a new numpy array with evenly spaced numbers over a given interval.
The general form is :

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```

The linspace() works like the arange() function. But instead of specifying the step size, `it defines the number of elements in the interval between the start and stop values`. You can notice the default num value is 50, which means you will have 50 elements in the array by default

In [12]:
# we will have 10 elements between 1 and 2
a3=np.linspace(1,2,10)

print(a3)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


If you don’t want to include the stop value, you can exclude it using the endpoint parameter. For example:

In [13]:
a = np.linspace(1, 2, 10, endpoint=False)

print(a)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
