# 3. NumPy Array Indexing and Slicing

Like a list, you can use the square bracket notation ([]) and index to access elements of a numpy array.

## 3.1 1-D array indexing

For a 1-D array, it's similar to python built-in list. `The first element starts with index 0, the second element starts with index 1, and so on. the last element has an index -1, the second last element has an index -2, and so on`.

In [1]:
import numpy as np

In [3]:
a=np.arange(0,5)

In [4]:
print(a)

[0 1 2 3 4]


In [5]:
print(a[0])
print(a[4])



0
4


In [7]:
print(a[-5])
print(a[-1])

0
4


## 3.1 2-D array indexing

With 2-D and multidimensional arrays, you can select elements as you do with 1-D arrays but for each dimension (or axis).

In [9]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a.shape)

(2, 3)


In [10]:
# returns the first element of the first axis
print(a[0])  # [1 2 3]

# returns the second element of the first axis
print(a[1])  # [4 5 6]

[1 2 3]
[4 5 6]


In [11]:
# selects the first element of the first axis ([1 2 3]) and the first element of the second axis.
print(a[0, 0])  # 1
# 1 selects the second element of the first axis ([4 5 6]) and 0 selects the first element of the second axis.
print(a[1, 0])  # 4
# 0 selects the first element of the first axis ([1 2 3]) axis and 2 selects the third element of the second axis.
print(a[0, 2])  # 3
# 1 selects the second element of the first axis ([4 5 6]) and 2 selects the third element of the second axis.
print(a[1, 2])  # 6
# 0 selects the first element of the first axis ([1 2 3]) and -1 selects the last element of the second axis.
print(a[0, -1])  # 3
# 1 selects the second element of the first axis ([1 2 3]) and -1 selects the last element of the second axis.
print(a[1, -1])  # 6

1
4
3
6
3
6


## 3-D array indexing

In [12]:
a = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[5, 6], [7, 8], [9, 10]],
])

print(a.shape)

(2, 3, 2)


In [13]:
print(a[0, 0, 1])

2
